[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_limit = 30000000
gas_price = 5000000000  # 5 gwei

# BSC RPC URLs
[rpc_endpoints]
bsc = "https://bsc-dataseed.binance.org/"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"

# Etherscan API keys for verification
[etherscan]
bsc = { key = "${BSC_API_KEY}", url = "https://api.bscscan.com/api" }
bsc_testnet = { key = "${BSC_API_KEY}", url = "https://api-testnet.bscscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
